### PR TITLE
allow clients to specify no-pr-str-on-value

### PR DESCRIPTION
**Pull request by jaredly**

### CODE REVIEW

**Comment by jaredly** [comment]
I have a repl where I want to be able to have the return values be interactable -- expand/collapse etc, so I need access to the real return value

**Comment by arichiardi** [comment]
Cool! I want to see that :smile: Will merge in a sec, give me the time to setup the docs.

**Comment by arichiardi** [comment]
The `:no-pr-str-on-value` feature is in `0.1.5-SNAPSHOT` :wink:

**Comment by jaredly** [comment]
sweet thanks!

**Pull request merged**
