### PR TITLE
Add (require 'cljs.tools.reader) test

### PR DESCRIPTION
**Pull request by arichiardi**
Strange behavior here too, I want to see what happens in node `0.12.5`

### CODE REVIEW

**Comment by jaredly** [comment]
do you have a similar test for the browser? you said it was working for you there

**Comment by arichiardi** [comment]
Nope, but I tried Chromium, Chrome and Firefox (the one it the pic in the issue), we don't have yet `require` tests for browser

**Comment by jaredly** [comment]
iteresting. I wonder what's different about my setup

**Comment by arichiardi** [comment]
I really don't know but I can ask @tomasz-biernacki if he can test the same:

- take the jar for `tools.reader-1.0.0alpha2` from `.m2`
- copy the content of all the `clj` and `cljc` files to the correct location in `cljs/tools/reader/...` (if I remember correctly)
- eval `(require 'cljs.tools.reader)`

**Pull request closed without merging**
