### PR TITLE
Exclude resolve to avoid warning on compile

### PR DESCRIPTION
**Pull request by timothypratley**
Minor change to avoid a compiler warning when using replumb

### CODE REVIEW

**Comment by arichiardi** [comment]
The build is failing but I assume the change is good. Which ClojureScript version are you running against?
Also please let me know if you find some discrepancy in behavior if you are using newer versions of it ok? Thanks!

**Comment by timothypratley** [comment]
Hi @arichiardi 

Yes it works for me locally... I did a `lein install` and compiled my project with [org.clojure/clojurescript "1.9.908"] it just removes the warning message.

According to the build log it is failing due to a missing `nvm` ... node version manager perhaps? I'll try to understand that a bit more.

**Comment by timothypratley** [comment]
I think I see what I need to do, I will change .travis.yml in the pull request

**Comment by arichiardi** [comment]
Oh that's awesome thanks, I am sure it is not going to be the only thing.

For instance the compiler cache has changed format, so maybe you will need to comment out those tests (with a big TODO).
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by timothypratley** [comment]
well, changing the build file fixed it... yay :)

**Comment by arichiardi** [comment]
Wow awesome job thanks, I will publish asap

**Pull request merged**
